// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwsWiCarL2TwGbbjRNIZarMrSKWya8niY',
    appId: '1:96729474862:web:facb8ea521610a4aedfcbf',
    messagingSenderId: '96729474862',
    projectId: 'pagination-eceac',
    authDomain: 'pagination-eceac.firebaseapp.com',
    storageBucket: 'pagination-eceac.appspot.com',
    measurementId: 'G-10WZB42J43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgo0xxNc0y_rnfIJe7tDAm2QC_r3_Nvo',
    appId: '1:96729474862:android:d55a42f76297368cedfcbf',
    messagingSenderId: '96729474862',
    projectId: 'pagination-eceac',
    storageBucket: 'pagination-eceac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQCNmCEUp6pvXddJZc_w7pR0bs6Ic0h0',
    appId: '1:96729474862:ios:c77f56e12a19ec40edfcbf',
    messagingSenderId: '96729474862',
    projectId: 'pagination-eceac',
    storageBucket: 'pagination-eceac.appspot.com',
    iosClientId: '96729474862-j5ss5glpr3s7fva4ddrm6ohdt9r6918v.apps.googleusercontent.com',
    iosBundleId: 'com.example.paginationone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQCNmCEUp6pvXddJZc_w7pR0bs6Ic0h0',
    appId: '1:96729474862:ios:b0ab2fb16d02107bedfcbf',
    messagingSenderId: '96729474862',
    projectId: 'pagination-eceac',
    storageBucket: 'pagination-eceac.appspot.com',
    iosClientId: '96729474862-k6sepiavibk3j6h3ad86196ko1eo85rn.apps.googleusercontent.com',
    iosBundleId: 'com.example.paginationone.RunnerTests',
  );
}
